name: nextcloud-aio

services:
  nextcloud-aio-mastercontainer:
    image: ghcr.io/nextcloud-releases/all-in-one:latest
    init: true
    restart: always
    container_name: nextcloud-aio-mastercontainer
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    network_mode: bridge
    ports:
      - "8080:8080"
    environment:
      APACHE_PORT: ${APACHE_PORT}
      APACHE_IP_BINDING: ${APACHE_IP_BINDING}
      NEXTCLOUD_DATADIR: ${NEXTCLOUD_DATADIR}
      NEXTCLOUD_UPLOAD_LIMIT: ${NEXTCLOUD_UPLOAD_LIMIT}
      NEXTCLOUD_MAX_TIME: ${NEXTCLOUD_MAX_TIME}
      NEXTCLOUD_MEMORY_LIMIT: ${NEXTCLOUD_MEMORY_LIMIT}
      TALK_PORT: ${TALK_PORT}
      BORG_RETENTION_POLICY: ${BORG_RETENTION_POLICY}
      TZ: ${TZ}

  caddy:
    image: caddy:alpine
    restart: always
    container_name: caddy
    volumes:
      - caddy_certs:/certs
      - caddy_config:/config
      - caddy_data:/data
      - caddy_sites:/srv
    network_mode: host
    configs:
      - source: Caddyfile
        target: /etc/caddy/Caddyfile

configs:
  Caddyfile:
    content: |
      https://${NEXTCLOUD_DOMAIN}:443 {
        reverse_proxy localhost:${APACHE_PORT}
      }

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer
  caddy_certs:
  caddy_config:
  caddy_data:
  caddy_sites:
